const fs = require('fs');
var code = [];
code.push('function printReceipt(trip, passengers) {');
code.push('  var rows = "";');
code.push('  for(var i=1; i<=7; i++){');
code.push('    var p = passengers[i-1] || {name:"", passport:"", nationality:""};');
code.push('    rows += "<tr><td>"+i+"</td><td>"+p.name+"</td><td>"+p.passport+"</td><td>"+p.nationality+"</td></tr>";');
code.push('  }');
code.push('  var now = new Date();');
code.push('  var timeStr = String(now.getHours()).padStart(2,"0")+":"+String(now.getMinutes()).padStart(2,"0");');
code.push('  var dateStr = now.getFullYear()+"/"+String(now.getMonth()+1).padStart(2,"0")+"/"+String(now.getDate()).padStart(2,"0");');
code.push('  var style = "<style>@page{size:A5;margin:10mm}body{font-family:Arial,sans-serif;direction:rtl;font-size:13px}.receipt{border:2px solid #000;padding:10px}.header{display:flex;justify-content:space-between;border-bottom:2px solid #000;padding-bottom:8px;margin-bottom:8px}.title{font-size:18px;font-weight:bold}.phone{background:#1a1a2e;color:white;padding:3px 8px;border-radius:4px;font-size:12px}.number{color:red;font-size:18px;font-weight:bold}.subtitle{background:#f59e0b;color:white;text-align:center;padding:6px;font-weight:bold;margin:8px 0;border-radius:4px}.info-row{display:flex;justify-content:space-between;padding:4px 0;border-bottom:1px solid #ddd}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{border:1px solid #000;padding:5px;text-align:center;font-size:12px}th{background:#1a1a2e;color:#ffd700}.footer{text-align:center;margin-top:8px;font-size:11px}.page-break{page-break-after:always}</style>";');
code.push('  var card = "<div class=receipt>";');
code.push('  card += "<div class=header><div><div class=title>دەروازەی نێودەوڵەتی حاجی ئۆمەران</div>";');
code.push('  card += "<div>وێنەی بازگه &nbsp; تێرمینال &nbsp; <span class=number>ژمارە : "+trip.id+"</span></div></div>";');
code.push('  card += "<div class=phone>0750 235 3448</div></div>";');
code.push('  card += "<div class=subtitle>پسووڵەی دەرچوونی تاکسی بۆ ناو حاجی ئۆمەران</div>";');
code.push('  card += "<div class=info-row><span>کات ( "+timeStr+" )</span><span>ڕێکەوت : "+dateStr+"</span></div>";');
code.push('  card += "<div class=info-row>ناوی شۆفێر : "+trip.driver_name+"</div>";');
code.push('  card += "<div class=info-row><span>ئۆتۆمبێلی ژمارە : "+trip.driver_car+"</span><span>ڕۆیشتنی بۆ : "+trip.route_to+"</span></div>";');
code.push('  card += "<div class=info-row><span>ژ.م شۆفێر : "+trip.driver_phone+"</span><span>بڕی پارە : "+Number(trip.total_income).toLocaleString()+" IQD</span></div>";');
code.push('  card += "<table><thead><tr><th>ژ</th><th>ناوی گەشتیار</th><th>ژ.پاسەپۆرت</th><th>وڵاتنامە</th></tr></thead><tbody>"+rows+"</tbody></table>";');
code.push('  card += "<div class=footer>دەروازەی نێودەوڵەتی حاجی ئۆمەران - تێرمینال</div></div>";');
code.push('  var w = window.open("", "_blank");');
code.push('  w.document.write("<!DOCTYPE html><html><head><meta charset=UTF-8>"+style+"</head><body>"+card+"<div class=page-break></div>"+card+"</body></html>");');
code.push('  w.document.close();');
code.push('  setTimeout(function(){w.print();}, 800);');
code.push('}');
require('fs').writeFileSync('frontend/js/receipt.js', code.join('\n'), 'utf8');
console.log('RECEIPT.JS FIXED!');
