const fs = require('fs');

fs.writeFileSync('frontend/js/new-trip.js', [
"var API = 'http://localhost:3000/api';",
"var tripType = '', tripId = null, passengers = [];",
"function updateClock(){var n=new Date(),e=document.getElementById('clock');if(e)e.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0');}",
"setInterval(updateClock,1000);updateClock();",
"function setType(btn,type){tripType=type;document.querySelectorAll('.btn-group .btn').forEach(b=>b.style.opacity='0.5');btn.style.opacity='1';document.getElementById('trip-form').style.display='block';document.getElementById('form-title').textContent=type+' - Details';document.getElementById('passenger-section').style.display='none';tripId=null;passengers=[];}",
"async function searchDriver(q){var box=document.getElementById('driver-suggest');if(q.length<2){box.style.display='none';return;}var res=await fetch(API+'/drivers/search?q='+encodeURIComponent(q));var data=await res.json();if(!data.success||!data.data.length){box.style.display='none';return;}box.innerHTML=data.data.map(d=>'<div class=\"suggest-item\" onclick=\"selectDriver('+JSON.stringify(d)+')\">'+ d.name+' - '+d.car_number+'</div>').join('');box.style.display='block';}",
"function selectDriver(d){document.getElementById('driver-name').value=d.name;document.getElementById('driver-phone').value=d.phone;document.getElementById('driver-car').value=d.car_number;document.getElementById('driver-suggest').style.display='none';}",
"async function startTrip(){var name=document.getElementById('driver-name').value.trim();var from=document.getElementById('route-from').value.trim();var to=document.getElementById('route-to').value.trim();if(!name||!from||!to){alert('Fill driver name and route!');return;}var phone=document.getElementById('driver-phone').value.trim();var car=document.getElementById('driver-car').value.trim();if(phone&&car&&confirm('Save driver for future?')){await fetch(API+'/drivers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone,car_number:car})});}var res=await fetch(API+'/trips',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:tripType,driver_name:name,driver_phone:phone,driver_car:car,route_from:from,route_to:to,fare_per_person:document.getElementById('fare').value||0})});var data=await res.json();if(data.success){tripId=data.data.id;document.getElementById('passenger-section').style.display='block';document.getElementById('bus-bulk').style.display=tripType==='Bus'?'block':'none';document.getElementById('single-passenger').style.display=tripType==='Bus'?'none':'block';alert('Trip started! ID:'+tripId);}else{alert('Error:'+data.error);}}",
"async function addPassenger(){var name=document.getElementById('pax-name').value.trim();if(!name){alert('Enter name!');return;}var passport=document.getElementById('pax-passport').value.trim();var res=await fetch(API+'/passengers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_id:tripId,name,passport})});var data=await res.json();if(data.success){passengers.push({name,passport});renderPassengers();document.getElementById('pax-name').value='';document.getElementById('pax-passport').value='';}}",
"async function addBulkPassengers(){var text=document.getElementById('bulk-text').value.trim();if(!text){alert('Paste list!');return;}var lines=text.split('\\n').filter(l=>l.trim());var paxList=lines.map(l=>{var p=l.split('-');return{name:(p[0]||l).trim(),passport:(p[1]||'').trim()};});var res=await fetch(API+'/passengers/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_id:tripId,passengers:paxList})});var data=await res.json();if(data.success){passengers=paxList;renderPassengers();alert(paxList.length+' added!');}}",
"function renderPassengers(){var list=document.getElementById('passenger-list');list.innerHTML='<h3 style=\"margin-bottom:10px\">Passengers: '+passengers.length+'</h3>'+passengers.map((p,i)=>'<div class=\"passenger-item\"><span class=\"passenger-num\">'+(i+1)+'</span><span>'+p.name+'</span><span>'+p.passport+'</span></div>').join('');}",
"async function finishTrip(){if(!tripId){alert('No trip!');return;}if(!passengers.length){alert('Add passengers!');return;}var res=await fetch(API+'/trips/'+tripId+'/complete',{method:'PUT',headers:{'Content-Type':'application/json'}});var data=await res.json();if(data.success){alert('Trip completed!');resetForm();}}",
"function resetForm(){['driver-name','driver-phone','driver-car','route-from','route-to','fare'].forEach(id=>document.getElementById(id).value='');document.getElementById('trip-form').style.display='none';document.getElementById('passenger-section').style.display='none';tripId=null;passengers=[];}"
].join('\n'), 'utf8');

fs.writeFileSync('frontend/js/active-trips.js', [
"var API = 'http://localhost:3000/api';",
"function updateClock(){var n=new Date(),e=document.getElementById('clock');if(e)e.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0');}",
"setInterval(updateClock,1000);updateClock();",
"async function loadActive(){var res=await fetch(API+'/trips/active');var data=await res.json();var tbody=document.getElementById('active-tbody');if(!data.success||!data.data.length){tbody.innerHTML='<tr><td colspan=\"9\" style=\"text-align:center;padding:30px\">No active trips</td></tr>';return;}tbody.innerHTML=data.data.map(t=>'<tr><td>'+t.id+'</td><td>'+t.type+'</td><td>'+t.driver_name+'</td><td>'+t.driver_car+'</td><td>'+t.route_from+' to '+t.route_to+'</td><td>'+t.passengers_count+'</td><td>'+Number(t.total_income).toLocaleString()+' IQD</td><td>'+new Date(t.start_time).toLocaleTimeString()+'</td><td><button class=\"btn btn-success\" onclick=\"completeTrip('+t.id+')\" style=\"padding:6px 12px;font-size:12px\">Complete</button> <button class=\"btn btn-danger\" onclick=\"deleteTrip('+t.id+')\" style=\"padding:6px 12px;font-size:12px\">Delete</button></td></tr>').join('');}",
"async function completeTrip(id){if(!confirm('Complete?'))return;await fetch(API+'/trips/'+id+'/complete',{method:'PUT',headers:{'Content-Type':'application/json'}});loadActive();}",
"async function deleteTrip(id){if(!confirm('Delete?'))return;await fetch(API+'/trips/'+id,{method:'DELETE'});loadActive();}",
"loadActive();setInterval(loadActive,10000);"
].join('\n'), 'utf8');

fs.writeFileSync('frontend/js/history.js', [
"var API = 'http://localhost:3000/api';",
"function updateClock(){var n=new Date(),e=document.getElementById('clock');if(e)e.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0');}",
"setInterval(updateClock,1000);updateClock();",
"async function loadHistory(){var date=document.getElementById('filter-date').value;var res=await fetch(API+'/trips/history'+(date?'?date='+date:''));var data=await res.json();var tbody=document.getElementById('history-tbody');if(!data.success||!data.data.length){tbody.innerHTML='<tr><td colspan=\"9\" style=\"text-align:center;padding:30px\">No trips found</td></tr>';return;}tbody.innerHTML=data.data.map(t=>'<tr><td>'+t.id+'</td><td>'+t.type+'</td><td>'+t.driver_name+'</td><td>'+t.route_from+' to '+t.route_to+'</td><td>'+t.passengers_count+'</td><td>'+Number(t.total_income).toLocaleString()+' IQD</td><td>'+t.status+'</td><td>'+new Date(t.start_time).toLocaleDateString()+'</td><td><button class=\"btn btn-danger\" onclick=\"deleteTrip('+t.id+')\" style=\"padding:6px 12px;font-size:12px\">Delete</button></td></tr>').join('');}",
"async function deleteTrip(id){if(!confirm('Delete?'))return;await fetch(API+'/trips/'+id,{method:'DELETE'});loadHistory();}",
"loadHistory();"
].join('\n'), 'utf8');

fs.writeFileSync('frontend/js/drivers.js', [
"var API = 'http://localhost:3000/api', allDrivers = [];",
"function updateClock(){var n=new Date(),e=document.getElementById('clock');if(e)e.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0');}",
"setInterval(updateClock,1000);updateClock();",
"async function loadDrivers(){var res=await fetch(API+'/drivers');var data=await res.json();allDrivers=data.data||[];renderDrivers(allDrivers);}",
"function renderDrivers(drivers){var tbody=document.getElementById('drivers-tbody');if(!drivers.length){tbody.innerHTML='<tr><td colspan=\"6\" style=\"text-align:center;padding:30px\">No drivers</td></tr>';return;}tbody.innerHTML=drivers.map(d=>'<tr><td>'+d.id+'</td><td>'+d.name+'</td><td>'+d.phone+'</td><td>'+d.car_number+'</td><td><span class=\"badge badge-active\">Active</span></td><td><button class=\"btn btn-danger\" onclick=\"deleteDriver('+d.id+')\" style=\"padding:6px 12px;font-size:12px\">Delete</button></td></tr>').join('');}",
"function filterDrivers(q){if(!q){renderDrivers(allDrivers);return;}renderDrivers(allDrivers.filter(d=>d.name.toLowerCase().includes(q.toLowerCase())||d.car_number.toLowerCase().includes(q.toLowerCase())));}",
"async function saveDriver(){var name=document.getElementById('drv-name').value.trim();var phone=document.getElementById('drv-phone').value.trim();var car=document.getElementById('drv-car').value.trim();if(!name||!phone||!car){alert('Fill all!');return;}var res=await fetch(API+'/drivers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone,car_number:car})});var data=await res.json();if(data.success){document.getElementById('drv-name').value='';document.getElementById('drv-phone').value='';document.getElementById('drv-car').value='';loadDrivers();alert('Saved!');}}",
"async function deleteDriver(id){if(!confirm('Delete?'))return;await fetch(API+'/drivers/'+id,{method:'DELETE'});loadDrivers();}",
"loadDrivers();"
].join('\n'), 'utf8');

fs.writeFileSync('frontend/js/reports.js', [
"var API = 'http://localhost:3000/api';",
"function updateClock(){var n=new Date(),e=document.getElementById('clock');if(e)e.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0');}",
"setInterval(updateClock,1000);updateClock();",
"function fmt(n){return Number(n||0).toLocaleString()+' IQD';}",
"async function loadReport(){var date=document.getElementById('report-date').value||new Date().toISOString().split('T')[0];var res=await fetch(API+'/reports/daily?date='+date);var data=await res.json();if(!data.success)return;var ct={trips:0,passengers:0,income:0},ld={trips:0,passengers:0,income:0},bs={trips:0,passengers:0,income:0};data.data.forEach(r=>{if(r.type==='City Taxi')ct={trips:r.trips,passengers:r.passengers||0,income:r.income||0};if(r.type==='Long Distance')ld={trips:r.trips,passengers:r.passengers||0,income:r.income||0};if(r.type==='Bus')bs={trips:r.trips,passengers:r.passengers||0,income:r.income||0};});document.getElementById('r-ct-trips').textContent=ct.trips;document.getElementById('r-ct-pass').textContent=ct.passengers;document.getElementById('r-ct-inc').textContent=fmt(ct.income);document.getElementById('r-ld-trips').textContent=ld.trips;document.getElementById('r-ld-pass').textContent=ld.passengers;document.getElementById('r-ld-inc').textContent=fmt(ld.income);document.getElementById('r-bs-trips').textContent=bs.trips;document.getElementById('r-bs-pass').textContent=bs.passengers;document.getElementById('r-bs-inc').textContent=fmt(bs.income);document.getElementById('r-tot-trips').textContent=ct.trips+ld.trips+bs.trips;document.getElementById('r-tot-pass').textContent=ct.passengers+ld.passengers+bs.passengers;document.getElementById('r-tot-inc').textContent=fmt(ct.income+ld.income+bs.income);}",
"function printReport(){window.print();}",
"async function exportCSV(){var date=document.getElementById('report-date').value||new Date().toISOString().split('T')[0];var res=await fetch(API+'/reports/export?date='+date);var data=await res.json();if(!data.success||!data.data.length){alert('No data!');return;}var headers=Object.keys(data.data[0]);var csv=[headers.join(','),...data.data.map(r=>headers.map(h=>r[h]).join(','))].join('\\n');var blob=new Blob([csv],{type:'text/csv'});var url=URL.createObjectURL(blob);var a=document.createElement('a');a.href=url;a.download='report-'+date+'.csv';a.click();URL.revokeObjectURL(url);}",
"document.getElementById('report-date').value=new Date().toISOString().split('T')[0];loadReport();"
].join('\n'), 'utf8');

console.log('ALL JS FILES DONE!');
