const fs = require('fs');
const nav = '<nav class="navbar"><div class="nav-brand">Terminal</div><div class="nav-links"><a href="../index.html">Dashboard</a><a href="new-trip.html">New Trip</a><a href="active-trips.html">Active Trips</a><a href="history.html">History</a><a href="drivers.html">Drivers</a><a href="reports.html">Reports</a></div><div class="nav-time" id="clock">--:--:--</div></nav>';
const head = (t,css) => '<!DOCTYPE html><html dir="rtl"><head><meta charset="UTF-8"><title>'+t+'</title><link rel="stylesheet" href="'+css+'css/style.css"></head><body>';

// ACTIVE TRIPS PAGE
fs.writeFileSync('frontend/pages/active-trips.html', head('Active Trips','../')+ nav+'<div class="container"><div class="page-header"><h1>Active Trips</h1></div><div class="table-card"><h2>Currently On Road</h2><div class="table-wrapper"><table><thead><tr><th>#</th><th>Type</th><th>Driver</th><th>Car</th><th>Route</th><th>Passengers</th><th>Income IQD</th><th>Started</th><th>Action</th></tr></thead><tbody id="active-tbody"><tr><td colspan="9" style="text-align:center;padding:30px">Loading...</td></tr></tbody></table></div></div></div><script src="../js/active-trips.js"></script></body></html>','utf8');

// HISTORY PAGE
fs.writeFileSync('frontend/pages/history.html', head('History','../')+ nav+'<div class="container"><div class="page-header"><h1>Trip History</h1></div><div class="form-card" style="margin-bottom:20px"><input type="date" id="filter-date" style="padding:10px;border:2px solid #e5e7eb;border-radius:8px;font-size:14px"> <button class="btn btn-primary" onclick="loadHistory()" style="margin-right:10px">Filter</button></div><div class="table-card"><div class="table-wrapper"><table><thead><tr><th>#</th><th>Type</th><th>Driver</th><th>Route</th><th>Passengers</th><th>Income IQD</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody id="history-tbody"><tr><td colspan="9" style="text-align:center;padding:30px">Loading...</td></tr></tbody></table></div></div></div><script src="../js/history.js"></script></body></html>','utf8');

// DRIVERS PAGE
fs.writeFileSync('frontend/pages/drivers.html', head('Drivers','../')+ nav+'<div class="container"><div class="page-header"><h1>Driver Management</h1></div><div class="form-card"><h2>Add New Driver</h2><div class="form-grid"><div class="form-group"><label>Driver Name</label><input type="text" id="drv-name" placeholder="Full name"></div><div class="form-group"><label>Phone</label><input type="text" id="drv-phone" placeholder="0750xxxxxxx"></div><div class="form-group"><label>Car Number</label><input type="text" id="drv-car" placeholder="ABC-123"></div></div><div class="btn-group"><button class="btn btn-success" onclick="saveDriver()">Save Driver</button></div></div><div class="table-card"><h2>All Drivers</h2><input type="text" id="driver-search" placeholder="Search drivers..." style="width:100%;padding:10px;border:2px solid #e5e7eb;border-radius:8px;margin-bottom:15px;font-size:14px" oninput="filterDrivers(this.value)"><div class="table-wrapper"><table><thead><tr><th>#</th><th>Name</th><th>Phone</th><th>Car</th><th>Status</th><th>Action</th></tr></thead><tbody id="drivers-tbody"><tr><td colspan="6" style="text-align:center;padding:30px">Loading...</td></tr></tbody></table></div></div></div><script src="../js/drivers.js"></script></body></html>','utf8');

// REPORTS PAGE
fs.writeFileSync('frontend/pages/reports.html', head('Reports','../')+ nav+'<div class="container"><div class="page-header"><h1>Daily Reports</h1></div><div class="form-card"><div style="display:flex;gap:15px;align-items:center"><input type="date" id="report-date" style="padding:10px;border:2px solid #e5e7eb;border-radius:8px;font-size:14px"><button class="btn btn-primary" onclick="loadReport()">Load Report</button><button class="btn btn-success" onclick="printReport()">Print Report</button><button class="btn btn-warning" onclick="exportCSV()">Export CSV</button></div></div><div id="report-content"><div class="stats-grid"><div class="stat-card taxi"><div class="stat-icon">🚕</div><div class="stat-title">City Taxi</div><div class="stat-row"><span>Trips:</span><span id="r-ct-trips">0</span></div><div class="stat-row"><span>Passengers:</span><span id="r-ct-pass">0</span></div><div class="stat-row income"><span>Income:</span><span id="r-ct-inc">0 IQD</span></div></div><div class="stat-card longdist"><div class="stat-icon">🚗</div><div class="stat-title">Long Distance</div><div class="stat-row"><span>Trips:</span><span id="r-ld-trips">0</span></div><div class="stat-row"><span>Passengers:</span><span id="r-ld-pass">0</span></div><div class="stat-row income"><span>Income:</span><span id="r-ld-inc">0 IQD</span></div></div><div class="stat-card bus"><div class="stat-icon">🚐</div><div class="stat-title">Bus</div><div class="stat-row"><span>Trips:</span><span id="r-bs-trips">0</span></div><div class="stat-row"><span>Passengers:</span><span id="r-bs-pass">0</span></div><div class="stat-row income"><span>Income:</span><span id="r-bs-inc">0 IQD</span></div></div><div class="stat-card total"><div class="stat-icon">💰</div><div class="stat-title">Total</div><div class="stat-row"><span>Trips:</span><span id="r-tot-trips">0</span></div><div class="stat-row"><span>Passengers:</span><span id="r-tot-pass">0</span></div><div class="stat-row income"><span>Income:</span><span id="r-tot-inc">0 IQD</span></div></div></div></div></div><script src="../js/reports.js"></script></body></html>','utf8');

console.log('ALL PAGES DONE!');
