const fs = require('fs');
fs.writeFileSync('frontend/js/receipt.js', [
"function printReceipt(trip, passengers) {",
"  var w = window.open('', '_blank', 'width=800,height=600');",
"  var rows = '';",
"  for(var i=1; i<=7; i++){",
"    var p = passengers[i-1] || {name:'', passport:'', nationality:''};",
"    rows += '<tr><td>'+i+'</td><td>'+p.name+'</td><td>'+p.passport+'</td><td>'+p.nationality+'</td></tr>';",
"  }",
"  var receipt = '<html><head><meta charset=UTF-8><style>",
"    @page{size:A5;margin:10mm}",
"    body{font-family:Arial,sans-serif;direction:rtl;font-size:13px;margin:0;padding:0}",
"    .receipt{border:2px solid #000;padding:10px;width:100%}",
"    .header{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #000;padding-bottom:8px;margin-bottom:8px}",
"    .title{font-size:18px;font-weight:bold;color:#1a1a2e}",
"    .phone{background:#1a1a2e;color:white;padding:3px 8px;border-radius:4px;font-size:12px}",
"    .number{color:red;font-size:20px;font-weight:bold}",
"    .subtitle{background:#f59e0b;color:white;text-align:center;padding:6px;font-weight:bold;margin:8px 0;border-radius:4px}",
"    .info-row{display:flex;justify-content:space-between;padding:4px 0;border-bottom:1px solid #ddd}",
"    table{width:100%;border-collapse:collapse;margin-top:10px}",
"    th,td{border:1px solid #000;padding:6px;text-align:center;font-size:12px}",
"    th{background:#1a1a2e;color:#ffd700}",
"    .footer{text-align:center;margin-top:10px;font-size:11px;color:#666}",
"    .page-break{page-break-after:always}",
"  </style></head><body>';",
"  var now = new Date();",
"  var timeStr = String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0');",
"  var dateStr = now.getFullYear()+'/'+String(now.getMonth()+1).padStart(2,'0')+'/'+String(now.getDate()).padStart(2,'0');",
"  var card = '<div class=receipt>'+",
"    '<div class=header>'+",
"    '<div><div class=title>دەروازەی نێودەوڵەتی حاجی ئۆمەران</div>'+",
"    '<div>وێنەی بازگه &nbsp;&nbsp; تێرمینال &nbsp;&nbsp; <span class=number>ژمارە : '+trip.id+'</span></div></div>'+",
"    '<div class=phone>0750 235 3448</div></div>'+",
"    '<div class=subtitle>پسووڵەی دەرچوونی تاکسی بۆ ناو حاجی ئۆمەران</div>'+",
"    '<div class=info-row><span>کات ( '+timeStr+' )</span><span>ڕێکەوت : '+dateStr+'</span></div>'+",
"    '<div class=info-row>ناوی شۆفێر : '+trip.driver_name+'</div>'+",
"    '<div class=info-row><span>ئۆتۆمبێلی ژمارە : '+trip.driver_car+'</span><span>ڕۆیشتنی بۆ : '+trip.route_to+'</span></div>'+",
"    '<div class=info-row><span>ژ.م شۆفێر : '+trip.driver_phone+'</span><span>بڕی پارە : '+Number(trip.total_income).toLocaleString()+' IQD</span></div>'+",
"    '<table><thead><tr><th>ژ</th><th>ناوی گەشتیار</th><th>ژ.پاسەپۆرت</th><th>وڵاتنامە</th></tr></thead><tbody>'+rows+'</tbody></table>'+",
"    '<div class=footer>دەروازەی نێودەوڵەتی حاجی ئۆمەران - تێرمینال</div>'+",
"    '</div>';",
"  w.document.write(receipt + card + '<div class=page-break></div>' + card + '</body></html>');",
"  w.document.close();",
"  setTimeout(function(){w.print();}, 500);",
"}"
].join('\n'), 'utf8');
console.log('RECEIPT.JS DONE!');
