var API = 'http://localhost:3000/api';
var tripType = '', tripId = null, passengers = [];
function updateClock(){var n=new Date(),e=document.getElementById('clock');if(e)e.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0');}
setInterval(updateClock,1000);updateClock();
function setType(btn,type){tripType=type;document.querySelectorAll('.btn-group .btn').forEach(b=>b.style.opacity='0.5');btn.style.opacity='1';document.getElementById('trip-form').style.display='block';document.getElementById('form-title').textContent=type+' - Details';document.getElementById('passenger-section').style.display='none';tripId=null;passengers=[];}
async function searchDriver(q){var box=document.getElementById('driver-suggest');if(q.length<2){box.style.display='none';return;}var res=await fetch(API+'/drivers/search?q='+encodeURIComponent(q));var data=await res.json();if(!data.success||!data.data.length){box.style.display='none';return;}box.innerHTML=data.data.map(d=>'<div class="suggest-item" onclick="selectDriver('+JSON.stringify(d)+')">'+ d.name+' - '+d.car_number+'</div>').join('');box.style.display='block';}
function selectDriver(d){document.getElementById('driver-name').value=d.name;document.getElementById('driver-phone').value=d.phone;document.getElementById('driver-car').value=d.car_number;document.getElementById('driver-suggest').style.display='none';}
async function startTrip(){var name=document.getElementById('driver-name').value.trim();var from=document.getElementById('route-from').value.trim();var to=document.getElementById('route-to').value.trim();if(!name||!from||!to){alert('Fill driver name and route!');return;}var phone=document.getElementById('driver-phone').value.trim();var car=document.getElementById('driver-car').value.trim();if(phone&&car&&confirm('Save driver for future?')){await fetch(API+'/drivers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone,car_number:car})});}var res=await fetch(API+'/trips',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:tripType,driver_name:name,driver_phone:phone,driver_car:car,route_from:from,route_to:to,fare_per_person:document.getElementById('fare').value||0})});var data=await res.json();if(data.success){tripId=data.data.id;document.getElementById('passenger-section').style.display='block';document.getElementById('bus-bulk').style.display=tripType==='Bus'?'block':'none';document.getElementById('single-passenger').style.display=tripType==='Bus'?'none':'block';alert('Trip started! ID:'+tripId);}else{alert('Error:'+data.error);}}
async function addPassenger(){var name=document.getElementById('pax-name').value.trim();if(!name){alert('Enter name!');return;}var passport=document.getElementById('pax-passport').value.trim();var res=await fetch(API+'/passengers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_id:tripId,name,passport})});var data=await res.json();if(data.success){passengers.push({name,passport});renderPassengers();document.getElementById('pax-name').value='';document.getElementById('pax-passport').value='';}}
async function addBulkPassengers(){var text=document.getElementById('bulk-text').value.trim();if(!text){alert('Paste list!');return;}var lines=text.split('\n').filter(l=>l.trim());var paxList=lines.map(l=>{var p=l.split('-');return{name:(p[0]||l).trim(),passport:(p[1]||'').trim()};});var res=await fetch(API+'/passengers/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_id:tripId,passengers:paxList})});var data=await res.json();if(data.success){passengers=paxList;renderPassengers();alert(paxList.length+' added!');}}
function renderPassengers(){var list=document.getElementById('passenger-list');list.innerHTML='<h3 style="margin-bottom:10px">Passengers: '+passengers.length+'</h3>'+passengers.map((p,i)=>'<div class="passenger-item"><span class="passenger-num">'+(i+1)+'</span><span>'+p.name+'</span><span>'+p.passport+'</span></div>').join('');}
async function finishTrip(){if(!tripId){alert('No trip!');return;}if(!passengers.length){alert('Add passengers!');return;}var res=await fetch(API+'/trips/'+tripId+'/complete',{method:'PUT',headers:{'Content-Type':'application/json'}});var data=await res.json();if(data.success){alert('Trip completed!');resetForm();}}
function resetForm(){['driver-name','driver-phone','driver-car','route-from','route-to','fare'].forEach(id=>document.getElementById(id).value='');document.getElementById('trip-form').style.display='none';document.getElementById('passenger-section').style.display='none';tripId=null;passengers=[];}
async function printCurrentReceipt(){if(!tripId){alert("No active trip!");return;}var res=await fetch("http://localhost:3000/api/trips/"+tripId);var data=await res.json();if(data.success){printReceipt(data.data,passengers);}}